ALTER TABLE PRODUCT ADD COLUMN DELETED BOOL DEFAULT FALSE;
ALTER TABLE CATEGORY ADD COLUMN DELETED BOOL DEFAULT FALSE;
ALTER TABLE MEDIA ADD COLUMN DELETED BOOL DEFAULT FALSE;
ALTER TABLE CART ADD COLUMN DELETED BOOL DEFAULT FALSE;
ALTER TABLE ROLES ADD COLUMN DELETED BOOL DEFAULT FALSE;
ALTER TABLE USER ADD COLUMN DELETED BOOL DEFAULT FALSE;
ALTER TABLE WAITER ADD COLUMN DELETED BOOL DEFAULT FALSE;
ALTER TABLE PLACE ADD COLUMN DELETED BOOL DEFAULT FALSE;
